all: openclose.c myread.c myread1.c rw.c draw.c
	gcc openclose.c -o openclose
	gcc myread.c -o myread
	gcc myread1.c -o myread1
	gcc rw.c -o rw
	gcc draw.c -o draw
clean:
	rm -f openclose myread myread1 rw draw *.o *~ image

